[package]
name = "adder"
version = "0.1.0"
authors = ["engineer"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
add-two = { path = "../add-two" }
